"""add:link_type

Revision ID: f459bfa772ef
Revises: 6fb8bfa35fe2
Create Date: 2026-05-23 20:53:20.414174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f459bfa772ef'
down_revision: Union[str, Sequence[str], None] = '6fb8bfa35fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('link_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'link_type')
    # ### end Alembic commands ###
